Repository jphacks/D_2001, pull requests merged in 2020-11, with the labels that each got.

#62 デザインで気になったところやenhancementを微調整しました
  src/assets/account_circle-24px (1).svg
  src/assets/app-logo-24px.svg
  src/assets/fact_check-24px.svg
  src/assets/login-icon-24px.svg
  src/assets/outbond-24px.svg
  src/assets/post-icon-24px.svg
  src/components/CustomHeader.vue
  src/components/Details/AnswerContent.vue
  src/components/Details/DetailsPage.vue
Labels: enhancement

#69 デザインを微調整しました
  src/assets/name_it_icon.png
  src/components/CustomHeader.vue
  src/components/Details/DetailsPage.vue
  src/components/Home/PostContent.vue
  src/components/Home/QuestionsList.vue
  src/components/Post/InputForm.vue
Labels: enhancement

#74 回答者が投票できるようになったところのスタイリング
  src/components/Details/AnswerContent.vue
  src/components/Details/DetailsPage.vue
Labels: enhancement

#80 各所に説明文などを入れていきます
  src/components/CustomHeader.vue
  src/components/Details/DetailsPage.vue
  src/components/Home/HomePage.vue
  src/components/Home/PostContent.vue
  src/components/Home/QuestionsList.vue
  src/components/Post/PostPage.vue
Labels: enhancement

#88 タイムスタンプ等々を整えました
  src/components/Details/AnswerContent.vue
  src/components/Home/HomePage.vue
  src/components/Home/PostContent.vue
Labels: enhancement

#91 CircleCI config.yml 修正(Firebse Hosting)
  .circleci/config.yml
  src/components/Details/DetailsPage.vue
  src/components/Home/PostContent.vue
  src/router/index.js
Labels: project setups

#106 v0.2分のスタイルを整えました
  public/favicon.ico
  src/assets/account_circle-24px (1).svg
  src/assets/app-logo-24px.svg
  src/assets/fact_check-24px.svg
  src/assets/invisible-star-24px.svg
  src/assets/outbond-24px.svg
  src/assets/star-24px.svg
  src/components/Details/CommentContent.vue
  src/components/Details/DetailsPage.vue
  src/components/Details/StarButton.vue
  src/components/Post/InputForm.vue
  src/components/Profile/ProfilePage.vue
Labels: enhancement

#113 v0.3分のスタイリングします
  package-lock.json
  src/assets/iconfinder_markdown_298823.svg
  src/components/Home/HomePage.vue
  src/components/Home/PostContent.vue
  src/components/Post/InputForm.vue
  src/components/Post/PostPage.vue
Labels: enhancement

#120 リリースv0.2のために戻します！
  package-lock.json
  package.json
  public/favicon.ico
  src/assets/account_circle-24px (1).svg
  src/assets/app-logo-24px.svg
  src/assets/fact_check-24px.svg
  src/assets/iconfinder_markdown_298823.svg
  src/assets/outbond-24px.svg
  src/components/CustomHeader.vue
  src/components/Details/AnswerContent.vue
  src/components/Details/CommentContent.vue
  src/components/Details/DetailsPage.vue
  src/components/Details/StarButton.vue
  src/components/Home/HomePage.vue
  src/components/Home/PostContent.vue
  src/components/Post/InputForm.vue
  src/components/Post/PostPage.vue
  src/components/Profile/ProfilePage.vue
  src/router/index.js
  src/store/index.js
Labels: P2

#122 readmeを編集しました
  README.md
Labels: enhancement

#123 Readmeの編集分をMasterに戻します
  README.md
Labels: enhancement

#125 ログインせずに詳細ページに行くと投票数がNaNになるバグの修正
  src/components/CustomHeader.vue
  src/components/Details/DetailsPage.vue
  src/components/Details/StarButton.vue
  src/store/index.js
Labels: P3
